FROM <python:3.9>


WORKDIR /home/maint_docker

COPY /home/maint_docker/deneme.launch.py


RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get update && \
    apt-get install vim nano git tmux wget curl python3-pip net-tools iputils-ping zsh psmisc -y


CMD ["python", "deneme.launch.py"]FROM <python:3.9>


WORKDIR /home/maint_docker

COPY /home/maint_docker/deneme.launch.py


RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get update && \
    apt-get install vim nano git tmux wget curl python3-pip net-tools iputils-ping zsh psmisc -y


CMD ["python", "deneme.launch.py"]
